### ISSUE TITLE
Python 3 Compatibility 

### ISSUE THREAD

**Issue by jmccartin** [GOFAI/glasstone#1]
First up, nice package, I'm quite interested in the science behind this and it's great to see it implemented in Python!

I've just tested all of the examples in a Python 3, and a couple of them fail due to the calls to xrange and keys.sort(), which are now deprecated in the language.  It's a pretty simple fix however, and doesn't break backwards compatibility to Python 2.7 or have any performance consequences.  I can make a pull request if you wish, but the changes are straighforward (all are in radiation.py I believe).

**Comment by GOFAI** [comment]
A pull request would be great, thanks!

**Comment by GOFAI** [comment]
Merged. Thanks!
