### ISSUE TITLE
Bug in dpt function in overpressure.py

### ISSUE THREAD

**Issue by rweed** [GOFAI/glasstone#6]
Hi. I recentely found your code while looking for info on nuclear blast effects and I believe there is a bug in _dpt. The function uses the variable t at line 555 in the overpressure.py source but it is never defined (that I can see) before it is used.  I presume its missing from the function argument list. ie the function definition should be ,
def _dpt(shob, sgr, x_m, ta_air, dp_q, pair, b, t): 
The function reference in _dynamicpressureatscaledtime should also be corrected.

BTW if you are looking for a report that has a (mostly) legible copy of the DNA 1KT standard Fortran source, look for  University of Toronto IAS Report UTIAS Technical Note. 259, April 1986 Title : "Quick Reproduction of Blast-wave Flow-Field Properties of Nuclear, TNT and ANFO Explosions" by Clinton P.T. Groth. I found a PDF vi Google Search

**Comment by GOFAI** [comment]
Thanks for pointing this out--I've gone ahead and committed the suggested changes to the master branch.
